Update patch set 4
Patch Set 4:

FYI the here's an example of the error on Windows with the FAST_PATH:

[ RUN      ] BlitFramebufferANGLETest.MultisampledRGBAToBGRA/ES2_D3D11_PRESENT_PATH_COPY
Message 0: ID3D11DeviceContext::Draw: The Shader Resource View dimension declared in the shader code (TEXTURE2D) does not match the view type bound to slot 0 of the Pixel Shader unit (TEXTURE2DMS).  This mismatch is invalid if the shader actually uses the view (e.g. it is not skipped due to shader code branching).
../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(630): error: Failed
1 D3D11 SDK Layers message(s) detected! Test Failed.

Patch-set: 4