Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.angle.try/win-msvc-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8825385694767808865
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/61] CXX obj/angle_glslang_wrapper/ShaderInterfaceVariableInfoMap.obj
    FAILED: obj/angle_glslang_wrapper/ShaderInterfaceVariableInfoMap.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/ShaderInterfaceVariableInfoMap.cpp(14): error C2220: the following warning is treated as an error
    ../../src/libANGLE/renderer/ShaderInterfaceVariableInfoMap.cpp(14): warning C5041: 'kInvalid': out-of-line definition for constexpr static data member is not needed and is deprecated in C++17
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8825385694767808817
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/61] CXX obj/angle_glslang_wrapper/ShaderInterfaceVariableInfoMap.obj
    FAILED: obj/angle_glslang_wrapper/ShaderInterfaceVariableInfoMap.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/ShaderInterfaceVariableInfoMap.cpp(14): error C2220: the following warning is treated as an error
    ../../src/libANGLE/renderer/ShaderInterfaceVariableInfoMap.cpp(14): warning C5041: 'kInvalid': out-of-line definition for constexpr static data member is not needed and is deprecated in C++17
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8825385694767808833
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [5/317] CXX obj/angle_glslang_wrapper/ShaderInterfaceVariableInfoMap.obj
    FAILED: obj/angle_glslang_wrapper/ShaderInterfaceVariableInfoMap.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/ShaderInterfaceVariableInfoMap.cpp(14): error C2220: the following warning is treated as an error
    ../../src/libANGLE/renderer/ShaderInterfaceVariableInfoMap.cpp(14): warning C5041: 'kInvalid': out-of-line definition for constexpr static data member is not needed and is deprecated in C++17
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1500872 \u003c1500872@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ dry run failed."}