Update patch set 1
Patch Set 1:

With "is_clang = false", I met the below error on my Ubuntu desktop:

[146/1759] CXX obj/angle_util_loader/gles_loader_autogen.o
FAILED: obj/angle_util_loader/gles_loader_autogen.o
g++ -MMD -MF obj/angle_util_loader/gles_loader_autogen.o.d -DLIBANGLE_UTIL_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DCR_SYSROOT_HASH=e7c53f04bd88d29d075bfd1f62b073aeb69cbe09 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DANGLE_USE_UTIL_LOADER -DANGLE_IS_64_BIT_CPU -DGL_GLES_PROTOTYPES=0 -DEGL_EGL_PROTOTYPES=0 -I../.. -Igen -I../.. -I../../include -I../../src -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wall -Werror -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-missing-field-initializers -Wno-unused-parameter -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf -fvisibility=hidden -std=gnu++14 -Wno-narrowing -fno-exceptions -fno-rtti --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../util/gles_loader_autogen.cpp -o obj/angle_util_loader/gles_loader_autogen.o
In file included from ../../util/gles_loader_autogen.cpp:11:0:
../../util/gles_loader_autogen.h:15:15: error: missing terminating ' character [-Werror]
 #    error Don't define GL prototypes if you want to use a loader!
               ^
cc1plus: all warnings being treated as errors
[155/1759] CXX obj/libANGLE/GLES1Renderer.o

Patch-set: 1
Reviewer: Gerrit User 1105324 <1105324@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gerrit User 1109831 <1109831@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0
Work-in-progress: false