WIP - Stand-alone build with gn.
Only tested on Linux so far.  Probably breaks the build within chrome.

Don't know why but doesn't seem to build the gtest versions of deqp.

You need a recent enough version of gn, this one will work on linux:
  ./buildtools/linux64/gn

The first time you 'gn gen' you may see something like:
  Missing sysroot (//build/linux/debian_jessie_amd64-sysroot). To fix, run: build/linux/sysroot_scripts/install-sysroot.py --arch=amd64

If you try to run the command as show, you may get this error:
  ImportError: No module named gyp

If so, try running it with PYTHONPATH in the environment, like this:
  PYTHONPATH=third_party/gyp/pylib build/linux/sysroot_scripts/install-sysroot.py --arch amd64

This CL is based on https://chromium-review.googlesource.com/c/angle/angle/+/403030
but I wasn't able to upload a new patch set there.

BUG=angleproject:1569

Change-Id: I56d19bec2d8b649a7bd65062c656cbfc69ea3dd8