Update patch set 9
Patch Set 9:

This CL has failed the run. Reason:

Tryjob [angle/try/win-msvc-x86-compile](https://cr-buildbucket.appspot.com/build/8799386916367194561) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[5/635] CXX obj/angle_image_util/AstcDecompressor.obj
FAILED: obj/angle_image_util/AstcDecompressor.obj
ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
../../src/image_util/AstcDecompressor.cpp(205): error C7555: use of designated initializers requires at least '/std:c++20'
```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 9
Attention: {"person_ident":"Gerrit User 1557704 \u003c1557704@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#9: Tryjobs failed"}