Add <cstring> include to FastVector.h
This resolves the call to `std::memcpy` which was failing in recent skia
skia rolls with an error that looked like this:

    error: no member named 'memcpy' in namespace 'std'; did you mean simply 'memcpy'?

Change-Id: If54ed266812315cfea35d95a57c758f75bcb270b