Cleanup: replace DirtyObjectType check with constexpr generator
Static assert was meant to avoid kDirtyObjectHandlers getting out of
sync, but it doesn't achieve that goal as it's just comparing values
with ints which is confusing.

Replacing with constexpr generated std::array. A missed handler yields
a compile error:

    error: constexpr variable 'kDirtyObjectHandlers' must be initialized by a constant expression

Bug: angleproject:8666
Bug: b/335295728
Change-Id: Idf9bbd087d09d5ba253a7587ce0503cae3fcf3a7