Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.angle.try/mac-test JOB_FAILED https://cr-buildbucket.appspot.com/build/8806580391623287505
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [184/326] CXX obj/libANGLE_with_capture/frame_capture_utils.o
    FAILED: obj/libANGLE_with_capture/frame_capture_utils.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    ../../src/libANGLE/capture/frame_capture_utils.cpp:339:11: error: no matching member function for call to 'addVector'
    json->addVector("DrawStates", framebufferState.getDrawBufferStates());
    ~~~~~~^~~~~~~~~
    ../../src/common/serializer/JsonSerializer.h:77:10: note: candidate template ignored: could not match 'vector' against 'FixedVector'
    void addVector(const std::string &name, const std::vector<T> &value)
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8806580391623287441
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [19/1115] CXX obj/libANGLE_with_capture/FrameCapture.obj
    FAILED: obj/libANGLE_with_capture/FrameCapture.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/FrameCapture.cpp(4156): error C2440: 'initializing': cannot convert from 'const angle::FixedVector<GLenum,8,std::array<T,8>>' to 'const std::vector<unsigned int,std::allocator<unsigned int>> &'
    with
    [
    T=GLenum
    ]
    ../../src/libANGLE/capture/FrameCapture.cpp(4157): note: Reason: cannot convert from 'const angle::FixedVector<GLenum,8,std::array<T,8>>' to 'const std::vector<unsigned int,std::allocator<unsigned int>>'
    with
    [
    T=GLenum
    ]
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/mac-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8806580391623287521
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [236/689] CXX obj/libANGLE_with_capture/frame_capture_utils.o
    FAILED: obj/libANGLE_with_capture/frame_capture_utils.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    ../../src/libANGLE/capture/frame_capture_utils.cpp:339:11: error: no matching member function for call to 'addVector'
    json->addVector("DrawStates", framebufferState.getDrawBufferStates());
    ~~~~~~^~~~~~~~~
    ../../src/common/serializer/JsonSerializer.h:77:10: note: candidate template ignored: could not match 'vector' against 'FixedVector'
    void addVector(const std::string &name, const std::vector<T> &value)
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8806580391623287457
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [220/380] CXX obj/libANGLE_with_capture/frame_capture_utils.obj
    FAILED: obj/libANGLE_with_capture/frame_capture_utils.obj
    C:\b\s\w\ir\cache\goma\client\gomacc.exe ..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.e...(too long)
    ../../src/libANGLE/capture/frame_capture_utils.cpp(339,11): error: no matching member function for call to 'addVector'
    json->addVector("DrawStates", framebufferState.getDrawBufferStates());
    ~~~~~~^~~~~~~~~
    ../../src\common/serializer/JsonSerializer.h(77,10): note: candidate template ignored: could not match 'vector' against 'FixedVector'
    void addVector(const std::string &name, const std::vector<T> &value)
    ^
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1000050 \u003c1000050@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ dry run failed."}