Update patch set 1
Patch Set 1:

Failed builds:
  luci.angle.try/winuwp-x64-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8834105153734852273
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [566/847] CXX obj/src/libANGLE/renderer/d3d/angle_d3d11_backend/InspectableNativeWindow.obj
    FAILED: obj/src/libANGLE/renderer/d3d/angle_d3d11_backend/InspectableNativeWindow.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    ../../src\libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.h(92): error C2220: the following warning is treated as an error
    ../../src\libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.h(92): warning C4091: '__declspec(uuid("7f924f66-ebae-40e5-a10b-b8f35e245190"))': ignored on left of 'rx::CoreWindowSizeChangedHandler' when no variable is declared
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.angle.try/winuwp-x64-dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8834105153734852289
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [541/847] CXX obj/src/libANGLE/renderer/d3d/angle_d3d11_backend/InspectableNativeWindow.obj
    FAILED: obj/src/libANGLE/renderer/d3d/angle_d3d11_backend/InspectableNativeWindow.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/d3d/d3d11/winrt/CoreWindowNativeWindow.h(92): error C2220: the following warning is treated as an error
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cv