Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Still getting this:
> ../../src/libANGLE/Config.cpp(75,77): error: extra ';' after member function definition [-Werror,-Wextra-semi]
>     NoConfig() { renderableType = EGL_OPENGL_ES3_BIT | EGL_OPENGL_ES2_BIT; };
>                                                                             ^
> ../../src/libANGLE/Config.cpp(76,3): error: declaration requires an exit-time destructor [-Werror,-Wexit-time-destructors]
> } g_NoConfigInstance;
>   ^
> ../../src/libANGLE/Config.cpp(76,3): error: declaration requires a global destructor [-Werror,-Wglobal-constructors]
> 3 errors generated.

Yep. Wasn't caught by MSVS. I have since, fixed and doing clang checks. We are reviewing the next change. Since no incarnation of static/constexpr resulted in no warnings/errors. I reverted to not using a singleton object, and just using EGL_NO_CONFIG_KHR as a constant nullptr. But we are reviewing this to see if it passes a taste test.

Patch-set: 1
Reviewer: Gerrit User 1359249 <1359249@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>