Switch merge to vpython3
merge broken by https://crrev.com/c/3600911 and that somehow doesn't
break builds, just says "json.output (invalid)" as the script raised
an exception:

ImportError: No module named pathlib

Bug: angleproject:6854
Change-Id: I38d72755ed9d1d0983439e017c616cfbe8c52b17