Update patch set 12
Patch Set 12:

Dry run: Failed builds:
  luci.angle.try/win-msvc-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8806193629053690177
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/472] CXX obj/libANGLE_with_capture/FrameCapture.obj
    FAILED: obj/libANGLE_with_capture/FrameCapture.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/FrameCapture.cpp(3617): error C2440: 'reinterpret_cast': cannot convert from 'T' to 'GLuint'
    with
    [
    T=uint32_t
    ]
    ../../src/libANGLE/capture/FrameCapture.cpp(3617): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ../../src/libANGLE/capture/FrameCapture.cpp(3667): error C4312: 'reinterpret_cast': conversion from 'GLuint' to 'EGLClientBuffer' of greater size
    ```
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8806193629053690129
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [30/564] CXX obj/libANGLE_with_capture/FrameCapture.obj
    FAILED: obj/libANGLE_with_capture/FrameCapture.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/FrameCapture.cpp(3617): error C2440: 'reinterpret_cast': cannot convert from 'T' to 'GLuint'
    with
    [
    T=uint32_t
    ]
    ../../src/libANGLE/capture/FrameCapture.cpp(3617): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ```
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 12
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1544099 \u003c1544099@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#12: CQ dry run failed."}