Update patch set 19
Patch Set 19:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8814275561815564225
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [91/110] CXX obj/src/tests/capture_replay_tests/angle_capture_replay_tests_fixture/trace_fixture.obj
    FAILED: obj/src/tests/capture_replay_tests/angle_capture_replay_tests_fixture/trace_fixture.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/trace_fixture.cpp(355): error C2440: 'reinterpret_cast': cannot convert from 'uint64_t' to 'uint64_t'
    ../../src/libANGLE/capture/trace_fixture.cpp(355): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 19
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1491823 \u003c1491823@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#19: CQ dry run failed."}