Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8817081460296167121
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [13/92] CXX obj/src/libANGLE/renderer/d3d/angle_d3d11_backend/RenderStateCache.obj
    FAILED: obj/src/libANGLE/renderer/d3d/angle_d3d11_backend/RenderStateCache.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/FramebufferImpl.h(120): error C2440: 'return': cannot convert from 'int' to 'const gl::InternalFormat &'
    C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/FramebufferImpl.h(120): note: Reason: cannot convert from 'int' to 'const gl::InternalFormat'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1000050 \u003c1000050@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ dry run failed."}