Update patch set 24
Patch Set 24:

A couple issues with the standalone GN build and MSVS:

* projects generate just fine
* when building, the first error I get is:

4>FAILED: obj/angle_common/PMurHash.obj
4>ninja -t msvc -e environment.x64 -- "c:\rnd\depot_tools\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/angle_common/PMurHash.obj.rsp /c ../../src/common/third_party/smhasher/src/PMurHash.cpp /Foobj/angle_common/PMurHash.obj /Fd"obj/angle_common_cc.pdb"
4>cl : Command line error D8022: cannot open 'obj/angle_common/PMurHash.obj.rsp'

More errors occur after that, such as 

4>FAILED: obj/angle_common/tls.obj
4>ninja -t msvc -e environment.x64 -- "c:\rnd\depot_tools\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/angle_common/tls.obj.rsp /c ../../src/common/tls.cpp /Foobj/angle_common/tls.obj /Fd"obj/angle_common_cc.pdb"
4>C:\Users\jmadill\Documents\Projects\ANGLEDev\angle\src\common\tls.cpp : fatal error C1083: Cannot open compiler generated file: 'C:\Users\jmadill\Documents\Projects\ANGLEDev\angle\out\msvs\obj\angle_common\tls.obj': Permission denied

* GN does not have the ability to contain multiple configs in one solution file. IE, Debug/Release/x86/x64. At least not as I was using it.

Patch-set: 24
Reviewer: Gerrit User 1105324 <1105324@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>