Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.angle.try/win-msvc-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8832357348661760561
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [21/93] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/RendererVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/RendererVk.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(647): error C2062: type 'void' unexpected
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(652): error C2143: syntax error: missing ';' before '{'
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(652): error C2447: '{': missing function header (old-style formal list?)
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(658): error C2062: type 'void' unexpected
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8832357348661760545
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [26/96] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/RendererVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/RendererVk.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(647): error C2062: type 'void' unexpected
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(652): error C2143: syntax error: missing ';' before '{'
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(652): error C2447: '{': missing function header (old-style formal list?)
    ../../src/libANGLE/renderer/vulkan/RendererVk.cpp(658): error C2062: type 'void' unexpected
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cv
Attention: {"person_ident":"Gerrit User 1392020 \u003c1392020@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: CQ dry run failed."}