Revert "D3D11: Reduce overhead of clearing unused textures."
Compile error on Windows:

error C2561: 'rx::Renderer11::clearTextures' : function must return a value

BUG=angleproject:959

This reverts commit 475e5b7f91f8ed9688b5a46efe54f15357096e3e.

Change-Id: Id34ff9530a71ce43549e2eb78d2d927084d46a47