Update patch set 3
Patch Set 3:

Error on fuchsia:

warning: Cannot merge binary files: scripts/run_code_generation_hashes.json (HEAD vs. 7b3b7d991... Add support for updating glslang_validator binary from Linux.)
error: could not apply 7b3b7d991... Add support for updating glslang_validator binary from Linux.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

No idea why this is only failing on fuchsia. It's very odd. I wonder if they're not using the right version of ANGLE?

Patch-set: 3
Reviewer: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>