Update patch set 1
Patch Set 1: Commit-Queue+1

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > I've run the deqp bots on your behalf. @Geoff Lang should be able to give you permission to run try jobs.
> > 
> > Thank you for the contribution. I just have a small request. Take a look at `src/tests/gl_tests/`. This is where our own end2end tests are located. A quick grep shows the following files using glBlendEquation:
> > 
> >     $ git grep "glBlendEquation\>"
> >     BlendFuncExtendedTest.cpp:        glBlendEquation(GL_FUNC_ADD);
> >     BlendMinMaxTest.cpp:            glBlendEquation(blendMin ? GL_MIN : GL_MAX);
> >     SimpleOperationTest.cpp:    glBlendEquation(GL_FUNC_ADD);
> >     WebGLCompatibilityTest.cpp:    glBlendEquation(GL_MIN);
> >     WebGLCompatibilityTest.cpp:    glBlendEquation(GL_MAX);
> >     WebGLCompatibilityTest.cpp:        glBlendEquation(GL_MIN);
> >     WebGLCompatibilityTest.cpp:        glBlendEquation(GL_MAX);
> > 
> > I can see that only `BlendMinMaxTest.cpp` needs modification with this change. Please add `ES3_VULKAN()` to the `ANGLE_INSTANTIATE_TEST()` macro at the end of that file.
> 
> Thank you for review. I added 'ES3_VULKAN()' to the 'ANGLE_INSTANTIATE_TEST()' macro and tested it. But, I got the following error in BlendMinMaxTest.RGBA16F (ES3_VULKAN) test case. (Only this test was failed.)
> 
> *********************************************************************
> ../../src/tests/gl_tests/BlendMinMaxTest.cpp(105): error: The difference between getExpected(blendMin, color.values[componentIdx], prevColor[componentIdx]) and pixel[componentIdx] is 42, which exceeds errorRange, where
> getExpected(blendMin, color.values[componentIdx], prevColor[componentIdx]) evaluates to -42,
> pixel[componentIdx] evaluates to 9.9071801427764567e-43, and
> errorRange evaluates to 0.0039215688593685627.
> ***********************************************************************
> 
> I think this is not related to this fix. Anyway, I will investigate this more.
> 
> And, I have one question. If I want to add this modification (BlendMinMaxTest.cpp) to this gerrit, is it ok to "git cl upload' again after 'git commit --amend' with this modification?
> 
> Thanks.

Ok, if those tests fail for other reasons, you don't need to enable them.

Regarding updating the cl, yes `git cl upload` would do the right thing. FYI, the `Change-Id: NNN` tag that's automatically added to the commit message is how `git cl upload` knows you are uploading the same CL.

Patch-set: 1
Reviewer: Gerrit User 1300114 <1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1