Revert "In D3D11 with DXGI1.2, use B5G6R5 for GL_RGB565"
Build break on Windows due to a rebase conflict (relocated header)

24>..\..\src\tests\gl_tests\SixteenBppTextureTest.cpp(9): fatal error C1083: Cannot open include file: 'end2end_tests/ANGLETest.h': No such file or directory

BUG=angleproject:1002
This reverts commit 5224926d11de22e6f0043d6b25ace7d3c4b60b28.

Change-Id: I4ed4e918ca5bcd85367ed3e364e29039fcdf5619