Update patch set 2
Patch Set 2:

It looks like this produced an unexpected failure in D3DTextureTest.TestD3D11SupportedFormats/ES2_OPENGL

https://chromium-swarm.appspot.com/task?id=39b9e3b8b3fdc310&refresh=10&show_raw=1

../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(51): error: Failed
LogGLDebugMessage(145): 
	Source: OpenGL
	Type: Error
	ID: 0x0502
	Severity: High
	Message: GL_INVALID_OPERATION error generated. Invalid format.
../../third_party/angle/src/tests/gl_tests/D3DTextureTest.cpp(285): error:       Expected: (0x3000)
      Which is: 12288
To be equal to: eglGetError()
      Which is: 12291

Can you investigate?

Patch-set: 2
Reviewer: Gerrit User 1105324 <1105324@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>