Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.angle.try/win-msvc-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8823524703963501089
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [265/301] CXX obj/src/tests/angle_white_box_tests/VulkanUniformUpdatesTest.obj
    FAILED: obj/src/tests/angle_white_box_tests/VulkanUniformUpdatesTest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/tests/gl_tests/VulkanUniformUpdatesTest.cpp(571): error C3493: 'kPosLoc' cannot be implicitly captured because no default capture mode has been specified
    ../../src/tests/gl_tests/VulkanUniformUpdatesTest.cpp(574): error C2665: 'CompileProgram': none of the 2 overloads could convert all the argument types
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1329751 \u003c1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}