Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x64-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8840285621372148449
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [18/1058] CXX obj/libANGLE_with_capture/FrameCapture.obj
    FAILED: obj/libANGLE_with_capture/FrameCapture.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/FrameCapture.cpp(5438): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cv