Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4:
> > > 
> > > I cannot run "git cl format" anymore. git cl format now execute scripts/export_targets.py and my local python cannot run this script. It reported:
> > > 
> > > ```
> > > File "scripts/export_targets.py", line 72
> > >     (OUT_DIR, *ROOTS) = sys.argv[1:]
> > >               ^
> > > SyntaxError: invalid syntax
> > > ```
> > > 
> > > Looks like star expression is python3 syntax but this script is written in python2?
> > 
> > Forget this, there is something messed up with my local python
> 
> Can you share the full text of the error in a gist? https://gist.github.com/
> 
> I am surprised that git cl format is running export_targets. It really shouldn't be doing that.

Ah, I see the problem. yapf can't handle formatting Python 3 right now. I filed http://anglebug.com/3985 . You should be able to work around this by temporarily reverting the changes to export_targets.py, running git cl format --full, then re-applying the changes to export_targets.py and re-uploading.

BTW when you are ready for review you can reply "Done" or leave another response to the comments I left. We don't get any email notification on new patch sets.

Patch-set: 5
Reviewer: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>