Update patch set 28
Patch Set 28:

Hi, all, the root-cause of failure is as below,
shader compilation failed: 0:13(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES.

Platform OpenGL version is lower than 4.3, but I do not think it is a mesa bug. I think it is not reasonable to use "IsIntel && IsOpenGL && IsLinux" to avoid test cases.
I had checked log, the machine(HasWell) has not "EGL_KHR_create_context" extension, but we use "ES31_OpenGL()" to create specifying context, it passed in "validateCreateContext" function and created context successfully, I think it is not correct.
The cases will be successfully skipped on my broadwell machine, it has the extension.
I think it is better to use "ES31_OpenGL(4,3), ES31_OpenGL(4, 4), ES31_OpenGL(4,5)" to initialize the test cases, though it is not fully correct. Do you think so?
OpenGL 4.2 with "ARB_compute_shader" also supports compute shader.

Patch-set: 28