Update patch set 1
Patch Set 1:

Looks like a lot of test failures:

[ RUN      ] dEQP.EGL/functional_swap_buffers_with_damage_resize_after_swap_render_render
dEQP-EGL.functional.swap_buffers_with_damage.resize_after_swap.render_render
WARN: setSwapBehavior(354): 	! Unimplemented: setSwapBehavior(../../third_party/angle/src/libANGLE/Surface.cpp:354)
../../third_party/angle/src/tests/deqp_support/angle_deqp_gtest.cpp(45): error: Failed
DebugUtilsMessenger(339): [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderArea ] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidRenderArea ] Object 0: handle = 0x410000000041, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x44824371 | Cannot execute a render pass with renderArea not within the bound of the framebuffer. RenderArea: x 0, y 0, width 960, height 240. Framebuffer: width 480, height 480.
                            Object: 0x410000000041 (type = Render Pass(18))

etc.

Design wise: instead of caching the DisplayVk, pass the egl::Display or gl::Context to getWidth/getHeight from the front-end.

Patch-set: 1
Reviewer: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>