Update patch set 1
Patch Set 1:

There error I see is:

../../third_party/angle/src/common/third_party/numerics/base/numerics/safe_math_impl.h:425:33: error: 'base::internal::CheckedNumericState<long unsigned int, (base::internal::NumericRepresentation)0u>::validity_' is too small to hold all values of 'enum base::internal::RangeConstraint' [-Werror]
     RangeConstraint validity_ : CHAR_BIT;  // Actually requires only two bits.

Which seems related to this patch. The logs can be a bit hard to parse, you'll need to look a bit farther up to see the actual error.

Patch-set: 1