Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > I cannot run "git cl format" anymore. git cl format now execute scripts/export_targets.py and my local python cannot run this script. It reported:
> > 
> > ```
> > File "scripts/export_targets.py", line 72
> >     (OUT_DIR, *ROOTS) = sys.argv[1:]
> >               ^
> > SyntaxError: invalid syntax
> > ```
> > 
> > Looks like star expression is python3 syntax but this script is written in python2?
> 
> Forget this, there is something messed up with my local python

Now I'm confused. The export_targets.py explicitly states python3 as its interpreter at the beginning. However, git cl format is from depot_tools. And depot_tools requires python2 not python3.

Patch-set: 4
Reviewer: Gerrit User 1374244 <1374244@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0