Revert "translator: Fix variable collection for gl_DepthRange."
Build errors on Linux:

error: comparison of integers of different signs: 'const int' and 'const unsigned int'

BUG=angleproject:991
BUG=478570

This reverts commit f1ae954b660cb058c40665b623f4d689b65180d4.

Change-Id: I217aba1b32dc0e70d6153337a1f0ccef0483a0e1