Update patch set 2
Patch Set 2:

[ RUN      ] TracePerfTest.Run/native_angry_birds_2_1500
API, Error, High: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
API, Error, High: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
../../third_party/angle/src/tests/perf_tests/ANGLEPerfTest.cpp(685): error: Expected equality of these values:
  static_cast<GLenum>(0)
    Which is: 0
  l_glGetError()
    Which is: 1282
Stack trace:
Backtrace:
	ANGLERenderTest::step [0x00007FF6F0DB4F8F+355] (o:\third_party\angle\src\tests\perf_tests\ANGLEPerfTest.cpp:685)
	ANGLEPerfTest::doRunLoop [0x00007FF6F0DB2D4A+74] (o:\third_party\angle\src\tests\perf_tests\ANGLEPerfTest.cpp:269)
	ANGLEPerfTest::run [0x00007FF6F0DB2C2C+76] (o:\third_party\angle\src\tests\perf_tests\ANGLEPerfTest.cpp:249)
	`anonymous namespace'::TracePerfTest_Run_Test::TestBody [0x00007FF6F0DE6206+22] (o:\third_party\angle\src\tests\perf_tests\TracePerfTest.cpp:350)

API, Error, High: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
API, Error, High: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error
Received fatal exception EXCEPTION_ACCESS_VIOLATION
Backtrace:
	memcpy_repmovs [0x00007FF6F20ABF4E+14] (d:\agent\_work\3\s\src\vctools\crt\vcruntime\src\string\amd64\memcpy.asm:114)
	angry_birds_2_1500::UpdateClientBufferData [0x00007FF6F0F61953+83] (o:\third_party\angle\src\tests\perf_tests\restricted_traces\angry_birds_2_1500\angry_birds_2_1500_capture_context3.cpp:161)
	angry_birds_2_1500::ReplayContext3Frame1501 [0x00007FF6F0E9BBA9+10025] (o:\third_party\angle\src\tests\perf_tests\restricted_traces\angry_birds_2_1500\angry_birds_2_1500_capture_context3_frame1501.cpp:194)
	angry_birds_2_1500::ReplayContext3Frame [0x00007FF6F0F614D5+69] (o:\third_party\angle\src\tests\perf_tests\restricted_traces\angry_birds_2_1500\angry_birds_2_1500_capture_context3.cpp:74)
	angle::ReplayFrame [0x00007FF6F0DE77F0+64] (o:\third_party\angle\src\tests\perf_tests\restricted_traces\restricted_traces_autogen.h:78)
	`anonymous namespace'::TracePerfTest::drawBenchmark [0x00007FF6F0DE6BB2+258] (o:\third_party\angle\src\tests\perf_tests\TracePerfTest.cpp:191)
	ANGLERenderTest::step [0x00007FF6F0DB4EBC+144] (o:\third_party\angle\src\tests\perf_tests\ANGLEPerfTest.cpp:678)
	ANGLEPerfTest::doRunLoop [0x00007FF6F0DB2D4A+74] (o:\third_party\angle\src\tests\perf_tests\ANGLEPerfTest.cpp:269)
	ANGLEPerfTest::run [0x00007FF6F0DB2C3D+93] (o:\third_party\angle\src\tests\perf_tests\ANGLEPerfTest.cpp:255)
	`anonymous namespace'::TracePerfTest_Run_Test::TestBody [0x00007FF6F0DE6206+22] (o:\third_party\angle\src\tests\perf_tests\TracePerfTest.cpp:350)
	testing::Test::Run [0x00007FF6F0DC9ED8+200] (o:\third_party\googletest\src\googletest\src\gtest.cc:2696)
	testing::TestInfo::Run [0x00007FF6F0DCA899+235] (o:\third_party\googletest\src\googletest\src\gtest.cc:2869)
	testing::TestSuite::Run [0x00007FF6F0DCB218+296] (o:\third_party\googletest\src\googletest\src\gtest.cc:3021)
	testing::internal::UnitTestImpl::RunAllTests [0x00007FF6F0DD4807+697] (o:\third_party\googletest\src\googletest\src\gtest.cc:5731)
	testing::UnitTest::Run [0x00007FF6F0DD44C7+209] (o:\third_party\googletest\src\googletest\src\gtest.cc:5313)
	base::TestSuite::Run [0x00007FF6F1F6FDAB+153] (o:\base\test\test_suite.cc:459)
	`anonymous namespace'::RunHelper [0x00007FF6F0D61110+68] (o:\gpu\angle_perftests_main.cc:16)
	base::OnceCallback<int ()>::Run [0x00007FF6F1F72E6D+53] (o:\base\callback.h:99)
	base::`anonymous namespace'::LaunchUnitTestsInternal [0x00007FF6F1F72217+271] (o:\base\test\launcher\unit_test_launcher.cc:165)
	base::LaunchUnitTestsSerially [0x00007FF6F1F7270B+134] (o:\base\test\launcher\unit_test_launcher.cc:244)
	main [0x00007FF6F0D610A3+163] (o:\gpu\angle_perftests_main.cc:34)
	__scrt_common_main_seh [0x00007FF6F20AB070+268] (d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
	BaseThreadInitThunk [0x00007FFC06623034+20]
	RtlUserThreadStart [0x00007FFC09021461+33]

Patch-set: 2