Revert "D3D: Move some varying packing code into a new file."
Compile error:

c:\b\build\slave\gpu_win_builder\build\src\third_party\angle\src\libangle\renderer\d3d\dynamichlsl.cpp(508) : error C3861: 'getSemanticInfo': identifier not found
c:\b\build\slave\gpu_win_builder\build\src\third_party\angle\src\libangle\renderer\d3d\dynamichlsl.cpp(642) : error C3861: 'getSemanticInfo': identifier not found

BUG=angleproject:1202

This reverts commit d992cde27ea6ffd71205399c3ddb88c7085c99b4.

Change-Id: I11f34d2ac4cc047c397e45348cb9502676380be0