Update patch set 2
Patch Set 2: Code-Review+1

LGTM when MSVC warning fixed:

../../src/libANGLE/VertexArray.cpp(170): error C2220: warning treated as error - no 'object' file generated
../../src/libANGLE/VertexArray.cpp(170): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
[6

Patch-set: 2
Reviewer: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1