Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8802886243374759281
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [72/1413] CXX obj/libANGLE_base/PixelLocalStorage.obj
    FAILED: obj/libANGLE_base/PixelLocalStorage.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/PixelLocalStorage.cpp(555): error C2440: 'initializing': cannot convert from '_OutIt' to 'GLenum *'
    with
    [
    _OutIt=std::_Array_iterator<GLenum,8>
    ]
    ../../src/libANGLE/PixelLocalStorage.cpp(555): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    ../../src/libANGLE/PixelLocalStorage.cpp(559): error C2672: 'std::fill': no matching overloaded function found
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1543967 \u003c1543967@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: CQ dry run failed."}