Update patch set 14
Patch Set 14: Commit-Queue+1

> Patch Set 13: Code-Review+1
> 
> (2 comments)
> 
> Excellent work, LGTM when compile error on VS 64-bit is fixed.
> 
> fyi MSVC error:
> 
> ../../src/libANGLE/renderer/vulkan/ProgramVk.cpp(437): error C4838: conversion from 'size_t' to 'uint32_t' requires a narrowing conversion

Hadn't uploaded the msvc fix so the latest PS would show the green bots without having to run them again ;)

Patch-set: 14
Reviewer: Gerrit User 1300114 <1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1