Android: Remove premake/LICENSE.txt from Android.bp
The ANGLE roll is failing in AOSP due to:

https://android-build.googleplex.com/builds/pending/P25700586/aosp_arm64-userdebug/latest/view/logs/build_error.log
    error: external/angle/Android.bp:7126:1: module
    "external_angle_license": module source path
    "external/angle/third_party/vulkan_memory_allocator/premake/LICENSE.txt"
    does not exist

The issue is that file was removed as part of the roll, so
scripts/generate_android_bp.py needs to be updated to remove the file
from the 'license_text' block.

Bug: angleproject:6356
Change-Id: I7db3a14ac07ea164deced630621bac2c26cd9d39