Revert "Gyp build support for Chrome OS."
http://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_chromeos_rel_ng/builds/189745

../../third_party/angle/src/libANGLE/renderer/gl/glx/DisplayGLX.cpp:87:27: error: assigning to 'Display *' (aka '_XDisplay *') from incompatible type 'EGLNativeDisplayType' (aka 'long')
    mXDisplay             = display->getNativeDisplayId();
                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/angle/src/libANGLE/renderer/gl/glx/DisplayGLX.cpp:93:19: error: comparison between pointer and integer ('Display *' (aka '_XDisplay *') and 'EGLNativeDisplayType' (aka 'long'))
    if (mXDisplay == EGL_DEFAULT_DISPLAY)
        ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~

BUG=angleproject:1297

This reverts commit b5aa26bda986d7f367ed4c33e50e931e9620abe9.

Change-Id: Icf3bd84df4493e66e78f8351b1a3879893ae9d0e