Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> I see this failure for example in the logs:
> 
> [ RUN      ] dEQP.GLES3/functional_texture_specification_basic_teximage2d_rgba32i_cube
> dEQP-GLES3.functional.texture.specification.basic_teximage2d.rgba32i_cube
> ../../third_party/angle/src/tests/deqp_support/angle_deqp_gtest.cpp(44): error: Failed
> forceChangeLayoutAndQueue(1815): 	! Assert failed in forceChangeLayoutAndQueue (../../third_party/angle/src/libANGLE/renderer/vulkan/vk_helpers.cpp:1815): transition.srcStageMask == transition.dstStageMask
> Stack trace:
> Backtrace:
> 
> Shabi any ideas?

Yes. `ImageMemoryBarrierData::isReadOnlyAccess` has changed to `ImageMemoryBarrierData::sameLayoutTransitionRequiresBarrier`. The layout that's added here should be setting this value to `false` after rebase.

Patch-set: 8
Reviewer: Gerrit User 1300114 <1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>