Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> (2 comments)
> 
> > Patch Set 3:
> > 
> > jamie, is there a way to decouple the two? i would like for the deps change not to hold up the checkin of the feature entirely. is it possible to do that as a follow up change?
> 
> Apologies Mohan. Please find the updated repository here:
> 
> https://chromium.googlesource.com/external/github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/
> 
> I included a BUILD.gn and README.chromium so it would be best to reuse this work instead of duplicating it by decoupling.

Including vk_mem_alloc.h file in third_party directory without modification causes dozens of errors in build. I guess coding style of VMA library is not go well with our build system. Is it possible to add a commit to get rid of errors in mirror repository? Or any better ideas?
Here are a part of errors we got during the build.
--------------------------
../../third_party/vulkan-memory-allocator/src\vk_mem_alloc.h(12906,80): error: missing field 'pNext' initializer [-Werror,-Wmissing-field-initializers]
        VkMappedMemoryRange memRange = { VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE };
                                                                               ^
../../third_party/vulkan-memory-allocator/src\vk_mem_alloc.h(15425,56): error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
    VMA_COPY_IF_NOT_NULL(vkGetPhysicalDeviceProperties);
--------------------------

Patch-set: 3
Reviewer: Gerrit User 1357791 <1357791@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>