Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Looks like this doesn't help.
> 
> [ RUN      ] CHROMIUMPathRenderingDrawTest.TestPathRenderingInstanced/ES2_VULKAN
> ../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(62): error: Failed
> initialize(530): ANGLE Display::initialize error 0: Internal Vulkan error: A requested extension is not supported., in ../../third_party/angle/src/libANGLE/renderer/vulkan/RendererVk.cpp, initialize:687.
> Stack trace:
> Backtrace:
> 	StackTraceGetter::CurrentStackTrace [0x00EEA978+40]
> 	testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop [0x00EF16C1+69]
> 	testing::internal::AssertHelper::operator= [0x00EF132C+48]
> 	ANGLETestEnvironment::GetWGLLibrary [0x00ED30C4+228]
> 	(No symbol) [0x731BA9E1]
> 	(No symbol) [0x7316F574]
> 	(No symbol) [0x73120743]
> 	(No symbol) [0x730410BD]
> 	EGLWindow::initializeDisplayAndSurface [0x741271D9+937]
> 
> ../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(447): error: Failed
> egl display or surface init failed.
> Stack trace:
> Backtrace:
> 	StackTraceGetter::CurrentStackTrace [0x00EEA978+40]
> 	testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop [0x00EF16C1+69]
> 	testing::internal::AssertHelper::operator= [0x00EF132C+48]
> 
> [  FAILED  ] CHROMIUMPathRenderingDrawTest.TestPathRenderingInstanced/ES2_VULKAN, where GetParam() = ES2_VULKAN (21 ms)
> 
> Going to see if complete revert works better.

No, it doesn't help that. This is in response to your suspicion that the tests are timing out due to the swap interval test. The failure above is an OOM issue.

Patch-set: 1
Reviewer: Gerrit User 1300114 <1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>