Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [angle/try/win-msvc-x86-dbg-compile](https://cr-buildbucket.appspot.com/build/8747297602147964385) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5554180?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[58/1484] CXX obj/angle_frame_capture_mock/FrameCapture_mock.obj
FAILED: obj/angle_frame_capture_mock/FrameCapture_mock.obj
ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
C:\b\s\w\ir\cache\builder\angle\src\libANGLE/State.h(1456): error C4573: the usage of 'gl::State::syncActiveTextures' requires the compiler to capture 'this' but the current default capture mode does not allow it
C:\b\s\w\ir\cache\builder\angle\src\libANGLE/State.h(1457): error C4573: the usage of 'gl::State::syncTexturesInit' requires the compiler to capture 'this' but the current default capture mode does not allow it
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/angle/buildbucket/cr-buildbucket/8747297602147964385/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1716323951
Attention: {"person_ident":"Gerrit User 1531247 \u003c1531247@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}