Add back sdk_version entry to build targets
Some targets in android repo are failing to compile
e.g. mainline_modules_arm64-trunk_staging-eng with
sdk_version entry removed from build_target.

Error message:
```
error: external/angle/Android.bp:8174:1: dependency
"libEGL_angle" of "ANGLE" missing variant:
  os:android,arch:arm64_armv8-a,sdk:sdk,link:shared
available variants:
  os:android,arch:arm64_armv8-a,link:shared
  os:android,arch:arm_armv8-a,link:shared
```

Add back sdk_version entry to the build targets.
END2END_TEST_TARGET needs to be disabled, because
with sdk_version entry added to END2END_TEST_TARGET,
the target failed to compile due to its' dependency
libgmock is missing the variant with sdk entry.

Bug: b/279980674
Change-Id: I96ea45b93519b84d72a70559d1ade9076ef9d955