Update patch set 1
Patch Set 1:

Failed builds:
  luci.angle.try/winuwp-x64-dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8846096161336565824
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/32] CC obj/third_party/zlib/miniunz_bin/miniunz.obj
    FAILED: obj/third_party/zlib/miniunz_bin/miniunz.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    ../../third_party/zlib/contrib/minizip/miniunz.c(93): error C2220: the following warning is treated as an error
    ../../third_party/zlib/contrib/minizip/miniunz.c(93): warning C4013: 'CreateFileA' undefined; assuming extern returning int
    ../../third_party/zlib/contrib/minizip/miniunz.c(94): warning C4047: '=': 'HANDLE' differs in levels of indirection from 'int'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run