Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [angle/try/win-msvc-x86-dbg-compile](https://cr-buildbucket.appspot.com/build/8768143276901504689) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4911957?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[6/156] CXX obj/third_party/vulkan-deps/vulkan-utility-libraries/src/vulkan_layer_settings/stub.obj
FAILED: obj/third_party/vulkan-deps/vulkan-utility-libraries/src/vulkan_layer_settings/stub.obj
ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
C:\b\s\w\ir\cache\builder\angle\third_party\vulkan-deps\vulkan-utility-libraries\src\include\vulkan/utility/vk_struct_helper.hpp(1179): error C2766: explicit specialization; 'VkObjectType vku::GetObjectType<VkBuffer>(void)' has already been defined
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run:1696443970