Update patch set 3
Patch Set 3:

> Patch Set 2: -Code-Review
> 
> ../../src/libANGLE/renderer/vulkan/RenderTargetVk.cpp:66:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
>     ensureImageInitialized(contextVk);
>     ^~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~
> ../../src/libANGLE/renderer/vulkan/RenderTargetVk.cpp:91:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
>     ensureImageInitialized(contextVk);
>     ^~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~

Courtney, you would need to make the functions return `angle::Result`. Then use `ANGLE_TRY(ensure...)`.

The graph looks good now, BTW, never mind the `finishCurrentCommands`.

Patch-set: 3
Reviewer: Gerrit User 1300114 <1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>