Update patch set 13
Patch Set 13: Code-Review+1

(2 comments)

Excellent work, LGTM when compile error on VS 64-bit is fixed.

fyi MSVC error:

../../src/libANGLE/renderer/vulkan/ProgramVk.cpp(437): error C4838: conversion from 'size_t' to 'uint32_t' requires a narrowing conversion

Patch-set: 13
Reviewer: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1