Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8844768808142413616
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [47/141] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/vk_helpers.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/vk_helpers.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp(6817): error C4838: conversion from 'const uint32_t' to 'int32_t' requires a narrowing conversion
    ../../src/libANGLE/renderer/vulkan/vk_helpers.cpp(6817): error C4838: conversion from 'const uint32_t' to 'int32_t' requires a narrowing conversion
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run