Vulkan: Remove VerifyExtensionsPresent() checks
These checks are redundant; the vulkan loader will diagnose attempts
to enable extensions that are not available:

ERROR: loader_validate_instance_extensions: Extension fake_extension not found in list of known instance extensions.

This avoids aborting instance creation on Fuchsia, where some required
extensions are provided by layers and cannot be enumerated by
vkEnumerateInstanceExtensionProperties.

BUG=angleproject:2475
TEST=angle_end2end_tests on Fuchsia (with full series)

Change-Id: Ic8dcd5a3d4defa9bdc7c19762f0a2f69e08cb997