Disable treat_warnings_as_errors on MSVC builds
Chromium rolls into ANGLE are currently blocked due to:
    error C2220: the following warning is treated as an error
    warning C4068: unknown pragma 'GCC'

MSVC unsupported by Chromium since 2020:
    https://groups.google.com/a/chromium.org/g/chromium-dev/c/fuVUxe1q6EA

V8 dropped MSVC support in 2024:
    https://groups.google.com/g/v8-users/c/J8Q6VrX9e4M/

ANGLE currently does compile-only MSVC builds. This CL further relaxes
MSVC support by ignoring warnings.

Bug: angleproject:376074941
Change-Id: Id6327617fb95a4b19f64cfda13dbd68733c34aa5