GCC: Make some operators of QueueSerial non constexpr
Fix build breakage for GCC because of calling non constexpr function
from a constexpr function.
The error example:
third_party/angle/src/libANGLE/renderer/serial_utils.h:214:40:
error: call to non-'constexpr' function 'rx::Serial
rx::AtomicQueueSerialFixedArray::operator[](rx::SerialIndex) const'

Bug: chromium:819294
Change-Id: Ic09be54ce9418ab3f7d947eaa27c97b55c3c2bab