Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.angle.try/winuwp-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8825675237576290625
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [9/16] CXX obj/libGLESv2_capture_complement/global_state.obj
    FAILED: obj/libGLESv2_capture_complement/global_state.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_toolchain\vs_files\3bda71a11e\VC\Tools\MSVC\14.26.28801\include\atomic(1437): error C2338: atomic<T> requires T to be trivially copyable, copy constructible, move constructible, copy assignable, and move assignable.
    ../../src/libGLESv2/global_state.cpp(245): note: see reference to class template instantiation 'std::atomic<angle::GlobalMutex>' being compiled
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8825675237576290705
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [30/66] CXX obj/libGL/global_state.obj
    FAILED: obj/libGL/global_state.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_toolchain\vs_files\3bda71a11e\VC\Tools\MSVC\14.26.28801\include\atomic(1437): error C2338: atomic<T> requires T to be trivially copyable, copy constructible, move constructible, copy assignable, and move assignable.
    ../../src/libGLESv2/global_state.cpp(245): note: see reference to class template instantiation 'std::atomic<angle::GlobalMutex>' being compiled
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/winuwp-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8825675237576290641
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [9/16] CXX obj/libGLESv2/global_state.obj
    FAILED: obj/libGLESv2/global_state.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_toolchain\vs_files\3bda71a11e\VC\Tools\MSVC\14.26.28801\include\atomic(1437): error C2338: atomic<T> requires T to be trivially copyable, copy constructible, move constructible, copy assignable, and move assignable.
    ../../src/libGLESv2/global_state.cpp(245): note: see reference to class template instantiation 'std::atomic<angle::GlobalMutex>' being compiled
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1175714 \u003c1175714@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}