Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8833391572833272097
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [128/218] CXX obj/src/tests/angle_white_box_perftests/VulkanPipelineCachePerf.obj
    FAILED: obj/src/tests/angle_white_box_perftests/VulkanPipelineCachePerf.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/tests/perf_tests/VulkanPipelineCachePerf.cpp(92): error C2440: 'reinterpret_cast': cannot convert from 'unsigned __int64' to 'VkShaderModule'
    ../../src/tests/perf_tests/VulkanPipelineCachePerf.cpp(92): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cv
Attention: {"person_ident":"Gerrit User 1329751 \u003c1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: CQ dry run failed."}