Update patch set 9
Patch Set 9:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8813613981160313761
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [253/355] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/TextureVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/TextureVk.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/vulkan/TextureVk.cpp(2693): error C2440: 'reinterpret_cast': cannot convert from 'HandleT' to 'uint64_t'
    with
    [
    HandleT=VkImage
    ]
    ../../src/libANGLE/renderer/vulkan/TextureVk.cpp(2693): note: Conversion is a valid standard conversion, which can be performed implicitly or by use of static_cast, C-style cast or function-style cast
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 9
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1511618 \u003c1511618@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#9: CQ dry run failed."}