Fix to build with VS2019
When building with VS2019 (using is_clang=false) multiples of the
following error are given:

    ../../src/common/mathutil.cpp(75): error C4244: '=':
    conversion from 'double' to 'float', possible loss of data

This is due to pow(), when passed an int for the second param, widens
the first param to a double (then returns a double).

Bug: angleproject:5521
Change-Id: Ic9e5eaedbe3fc7ceeed697898823b76dffcd989a