Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> What tests are failing?

A bunch of them, but mostly for the same reason. Example:

ShaderImageTest.ImageLoad:
Shader compilation failedERROR: 0:6: 'imageLoad' : no matching overloaded function found
ERROR: 0:6: '=' : dimension mismatch
ERROR: 0:6: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'
ERROR: 0:7: 'imageLoad' : no matching overloaded function found
ERROR: 0:7: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of int'

Mostly the errors are 'cannot convert from const mediump float to something else'.

I'm going to log all of the dynamic TType constructions and see if something changed there.

There are some crashes too (especially in constant folding tests) but I haven't been able to debug them yet.

Patch-set: 6
Reviewer: Gerrit User 1172235 <1172235@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>