Android: improve error message due to missing trace libs
I think this only happens when angle_restricted_traces wasn't set in gn
args, resulting in traces outside of the apk.

Previously we'd get a confusing error about missing gen/tracegz...
files, now we get this:

    I16:48:33.075615Z Syncing 1945_air_force trace (1/1)
    ...
    AssertionError: File not found (http://b/294861737 ?): libangle_restricted_traces_1945_air_force.so

Also removed swallowing errors in _PushLibToAppDir, crashing seems
better than running with out of date files.

Bug: b/294861737
Change-Id: I5696f35a910f6db2310d90e112a83881af3a8f50