Update patch set 3
Patch Set 3:

> Patch Set 2:
> 
> Welp, now it no longer builds in the build configs where UNREACHABLE() is noreturn:
> 
> 
> FAILED: obj/third_party/angle/translator/ParseContext.o 
> ../../third_party/angle/src/compiler/translator/ParseContext.cpp:4999:17: error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
>                 ANGLE_FALLTHROUGH;
>                 ^

Let's just remove the fallthrough case because it was just the one.  Let me know if you would like me to do it.

Patch-set: 3
Reviewer: Gerrit User 1105284 <1105284@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>