Update patch set 13
Patch Set 13:

> Patch Set 13:
> 
> > Patch Set 13:
> > 
> > (1 comment)
> > 
> > > Patch Set 12:
> > > 
> > > > Patch Set 12:
> > > > 
> > > > > Patch Set 12:
> > > > > 
> > > > > (8 comments)
> > > > > 
> > > > > Would be nice to have some examples that walk through the various transitions.
> > > > > Hard to visualize all the permutations just looking at the code.
> > > > 
> > > > The access bit and stage bit are not fully independent. Most of the access bit are specific to a stage. The shader access bit needs to combined with stage bit to form a unique readType/writeType. Then I can use the combination of these readType/writeType to form an index to do table lookup to see when that specific barrier has been issue. I am writing test to cover this.
> > > 
> > > +1 to request for clearly documented examples of GL code leading to Vulkan barrier calls
> > 
> > And even better, a perf test based on those examples that proves this code.
> 
> Thanks for letting me know, there is ~5% in TRex and Manhattan31, and ~9% in Mahattan30 FPS drop, and ~50% write bandwidth increase

Sorry, please ignore my above comment, there is a build error, so the result is incorrect
../../src/libANGLE/renderer/vulkan/ContextVk.cpp:3315:13: error: use of undeclared identifier 'mMemoryBarrierTracker'
             mMemoryBarrierTracker->reset();

Patch-set: 13