Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [angle/try/win-msvc-x86-compile](https://cr-buildbucket.appspot.com/build/8799332704858840785) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[259/458] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/vk_caps_utils.obj
FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/vk_caps_utils.obj
ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
../../src/libANGLE/renderer/vulkan/vk_caps_utils.cpp(342): error C7555: use of designated initializers requires at least '/std:c++20'
```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Attention: {"person_ident":"Gerrit User 1491687 \u003c1491687@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}