Revert "Add UBO offset support for D3D11.1."
Failed on 32-bit builds.  See: https://build.chromium.org/p/chromium.gpu.fyi/builders/GPU%20Win%20Builder/builds/24828/steps/compile/logs/stdio

angle\src\libangle\validationes.cpp(1461) : error C2220: warning treated as error - no 'object' file generated
angle\src\libangle\validationes.cpp(1461) : warning C4018: '<' : signed/unsigned mismatch

This reverts commit 381f969315c0c70bacf183e58de7194f42486112.

Change-Id: I05f09f19e40046994d34809c5b79095458f56148