Update patch set 1
Patch Set 1:

Failed builds:
  luci.angle.try/winuwp-x64-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8846097074287550800
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/232] CC obj/third_party/zlib/minizip_bin/minizip.obj
    FAILED: obj/third_party/zlib/minizip_bin/minizip.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    ../../third_party/zlib/contrib/minizip/minizip.c(88): error C2220: the following warning is treated as an error
    ../../third_party/zlib/contrib/minizip/minizip.c(88): warning C4013: 'FileTimeToDosDateTime' undefined; assuming extern returning int
    [4/232] CC obj/third_party/zlib/miniunz_bin/miniunz.obj
    FAILED: obj/third_party/zlib/miniunz_bin/miniunz.obj
    ninja -t msvc -e environment.store_x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\w...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run