Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [angle/try/win-msvc-x86-dbg-compile](https://cr-buildbucket.appspot.com/build/8797214897226119953) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[349/455] CXX obj/src/tests/angle_unittests/serial_utils_unittest.obj
FAILED: obj/src/tests/angle_unittests/serial_utils_unittest.obj
ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/serial_utils.h(188): error C2079: 'rx::QueueSerialFixedArray::mSerials' uses undefined class 'std::array<rx::Serial,1>'
C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/serial_utils.h(170): error C2109: subscript requires array or pointer type
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Attention: {"person_ident":"Gerrit User 1392020 \u003c1392020@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}