Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> > Patch Set 8:
> > 
> > > Patch Set 8:
> > > 
> > > Not sure how to progress here. I tried building and running the failing tests on my Linux machine, but either they pass for me, or I'm not running the same tests.
> > 
> > I'm a bit stumped now too.
> > 
> > I updated my GL driver so it has OVR_mutliview now too and still no repro (your function isn't even called)
> > 
> > Also no difference between debug and release builds
> 
> Nevermind, I figured it out.  Our GL backend exposes the multiview extension only when GL_NV_viewport_array2 is available (https://cs.chromium.org/chromium/src/third_party/angle/src/libANGLE/renderer/gl/renderergl_utils.cpp?l=1109) which is only available on Pascal+ NVidia GPUs (which our bots are).

We end up with compile errors in the GL driver when I force the GL backend to expose multiview:

        0(16) : error C7548: 'gl_ViewportIndex' requires "#extension GL_NV_viewport_array2 : enable" before use
        0(16) : error C7548: 'gl_ViewportIndex' requires "#extension GL_AMD_vertex_shader_viewport_index : enable" before use
        0(16) : error C7548: 'gl_ViewportIndex' requires "#extension GL_ARB_shader_viewport_layer_array : enable" before use
        0(20) : error C0000: ... or #extension GL_NV_viewport_array2 : enable
        0(20) : error C0000: ... or #extension GL_AMD_vertex_shader_layer : enable

I'm guessing there are other parts in the compiler code that assume we're doing the viewport layer emulation when multiview is being used.

Patch-set: 8
Reviewer: Gerrit User 1105284 <1105284@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0