Update patch set 1
Patch Set 1:

Failed builds:
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8829241338364279809
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [7/3166] CXX obj/angle_glslang_wrapper/glslang_wrapper_utils.obj
    FAILED: obj/angle_glslang_wrapper/glslang_wrapper_utils.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/glslang_wrapper_utils.cpp(4687): error C2220: the following warning is treated as an error
    ../../src/libANGLE/renderer/glslang_wrapper_utils.cpp(4687): warning C5041: 'kInvalid': out-of-line definition for constexpr static data member is not needed and is deprecated in C++17
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8829241338364279841
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [19/3135] CXX obj/angle_glslang_wrapper/glslang_wrapper_utils.obj
    FAILED: obj/angle_glslang_wrapper/glslang_wrapper_utils.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/glslang_wrapper_utils.cpp(4687): error C2220: the following warning is treated as an error
    ../../src/libANGLE/renderer/glslang_wrapper_utils.cpp(4687): warning C5041: 'kInvalid': out-of-line definition for constexpr static data member is not needed and is deprecated in C++17
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8829241338364279825
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [18/3158] CXX obj/angle_glslang_wrapper/glslang_wrapper_utils.obj
    FAILED: obj/angle_glslang_wrapper/glslang_wrapper_utils.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/renderer/glslang_wrapper_utils.cpp(4687): error C2220: the following warning is treated as an error
    ../../src/libANGLE/renderer/glslang_wrapper_utils.cpp(4687): warning C5041: 'kInvalid': out-of-line definition for constexpr static data member is not needed and is deprecated in C++17
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run