Revert "Re-enable 2DArray Copy Texture Tests"
This reverts commit 91b95ce0afbb55ebde1d39c2ed9632526ee365c5.

Reason for revert: Tests passing in release but failing in Debug.

https://ci.chromium.org/p/chromium/builders/luci.chromium.ci/Win10%20FYI%20Debug%20%28NVIDIA%29/2556

[ RUN      ] Texture2DArrayCopy.SnormFormats/ES3_D3D11
Error getting extension string from EGL Window.
../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(493): error: Expected equality of these values:
  (0x3000)
    Which is: 12288
  eglGetError()
    Which is: 12289
Stack trace:
Backtrace:
	StackTraceGetter::CurrentStackTrace [0x00AD4A9A+90]
	testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop [0x00AEAD5A+74]
	testing::internal::AssertHelper::operator= [0x00AEA86B+75]
	ANGLETestBase::swapBuffers [0x00A743C0+256]
	ANGLETestBase::ANGLETestTearDown [0x00A73817+167]
	ANGLETest::TearDown [0x00A7671A+26]
	angle::CopyTexture3DTest::TearDown [0x002A085D+29]

[  FAILED  ] Texture2DArrayCopy.SnormFormats/ES3_D3D11, where GetParam() = ES3_D3D11 (59 ms)
[----------] 1 test from Texture2DArrayCopy (59 ms total)

[----------] 3 tests from CubeMapTextureTest
[ RUN      ] CubeMapTextureTest.RenderToFacesConsecutively/ES2_D3D11_10_0
Assertion failed: mState.surfaceSet.empty(), file ../../third_party/angle/src/libANGLE/renderer/DisplayImpl.cpp, line 23
abort() has been called
Received fatal exception EXCEPTION_BREAKPOINT
Backtrace:

Original change's description:
> Re-enable 2DArray Copy Texture Tests
> 
> Re-enables 3 tests that were previously failing on Nvidia hardware on
> D3D11. The tests seem stable after a trybot driver update.
> 
> Bug: angleproject:2896
> Change-Id: I17d76a5a67fd57ba7257ef22aa5a1371bf5ed55e
> Reviewed-on: https://chromium-review.googlesource.com/c/1308735
> Commit-Queue: Jamie Madill <jmadill@chromium.org>
> Reviewed-by: Jamie Madill <jmadill@chromium.org>

TBR=geofflang@chromium.org,jmadill@chromium.org,brandon1.jones@intel.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: angleproject:2896
Change-Id: I509756e8e6433fd3d04bc68a72e7cc7647485b56