Revert "Add row-sharing packing tests for VariablePacker_test.cpp"
Failures on the GPU FYI waterfall:

angle\src\tests\compiler_tests\variablepacker_test.cpp(197) : error C2374: 'num_elements_per_array' : redefinition; multiple initialization

BUG=angleprojedt:1142

This reverts commit a9bee1b8e233e056c514198f5805a3d4ee3d8b48.

Change-Id: I94d569afb1b0c6ec2a00d0572f6eff2221c2ae60