Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x64-dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8843408217871366208
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/131] CXX obj/libANGLE_with_capture/FrameCapture.obj
    FAILED: obj/libANGLE_with_capture/FrameCapture.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/FrameCapture.cpp(3975): error C4838: conversion from 'GLint' to 'GLuint' requires a narrowing conversion
    ../../src/libANGLE/capture/FrameCapture.cpp(3986): error C4838: conversion from 'GLint' to 'GLuint' requires a narrowing conversion
    ../../src/libANGLE/capture/FrameCapture.cpp(4004): error C4838: conversion from 'GLint' to 'GLuint' requires a narrowing conversion
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.angle.try/win-msvc-x86-dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8843408217871366176
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [32/131] CXX obj/libANGLE_with_capture/FrameCapture.obj
    FAILED: obj/libANGLE_with_capture/FrameCapture.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/capture/FrameCapture.cpp(3975): error C4838: conversion from 'GLint' to 'GLuint' requires a narrowing conversion
    ../../src/libANGLE/capture/FrameCapture.cpp(3986): error C4838: conversion from 'GLint' to 'GLuint' requires a narrowing conversion
    ../../src/libANGLE/capture/FrameCapture.cpp(4004): error C4838: conversion from 'GLint' to 'GLuint' requires a narrowing conversion
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run