Update patch set 5
Patch Set 5:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x64-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8843591289016878096
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [93/1407] CXX obj/libANGLE_base/formatutils.obj
    FAILED: obj/libANGLE_base/formatutils.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src/libANGLE/formatutils.cpp(621): error C2398: Element '1': conversion from 'uint32_t' to 'int' requires a narrowing conversion
    ../../src/libANGLE/formatutils.cpp(622): error C2398: Element '2': conversion from 'uint32_t' to 'int' requires a narrowing conversion
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 5
Tag: autogenerated:cq:dry-run