Update patch set 1
Patch Set 1:

The good news is I get to practice `git try`.

C:\src\chrome\src\third_party\angle>git try
.gclient file in parent directory C:\src\chrome might not be the file you want to use
Results will be emailed to: thakis@chromium.org
WARNING: Could not read netrc file c:/src/depot_tools\_netrc
WARNING: Could not read netrc file c:/src/depot_tools\_netrc
Traceback (most recent call last):
  File "c:\src\depot_tools\git_try.py", line 75, in <module>
    sys.exit(main(sys.argv[1:]))
  File "c:\src\depot_tools\git_try.py", line 63, in main
    extra_epilog='\n'
  File "c:\src\depot_tools\trychange.py", line 1247, in TryChange
    sender(bot_spec, options)
  File "c:\src\depot_tools\trychange.py", line 804, in _SendChangeGerrit
    PostTryjob(message)
  File "c:\src\depot_tools\trychange.py", line 777, in PostTryjob
    labels={'Tryjob-Request': 1})
  File "c:\src\depot_tools\gerrit_util.py", line 563, in SetReview
    response = ReadHttpJsonResponse(conn)
  File "c:\src\depot_tools\gerrit_util.py", line 326, in ReadHttpJsonResponse
    conn, expect_status=expect_status, ignore_404=ignore_404)
  File "c:\src\depot_tools\gerrit_util.py", line 319, in ReadHttpResponse
    raise GerritError(response.status, reason)
gerrit_util.GerritError: Forbidden: Authentication required

Sending crash report ...

Patch-set: 1
Label: Code-Review=0