Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > The allocator is now accessible to DEPS here:
> > > 
> > > https://chromium.googlesource.com/external/github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/
> > > 
> > > If you use it please place it in angle/third_party/VulkanMemoryAllocator/src and put a README.chromium in angle/third_party/VulkanMemoryAllocator/
> > 
> > Now, I succeed to generate VMA repo in third_party directory using DEPS file. But there is one problem in accessing the header file in the third_party directory.
> > I modified BUILD.gn in angle root dir like this.
> > ----------------------------
> > @@ -609,6 +609,7 @@ angle_source_set("libANGLE_base") {
> > 
> >    if (angle_enable_vulkan) {
> >      public_deps += [ "src/libANGLE/renderer/vulkan:angle_vulkan_backend" ]
> > +    include_dirs += [ "//third_party/vulkan-memory-allocator/src/src" ]
> >    }
> > ------------------------------
> > But I got errors like below.
> > ------------------------------
> > ../../src\libANGLE/renderer/vulkan/vk_wrapper.h(18,10): fatal error: 'vk_mem_alloc.h' file not found
> > #include "vk_mem_alloc.h"
> > ------------------------------
> > Could you let me know What I missed?
> 
> Ah yes. I can help with this. Let me set it up properly for you, I have an idea.

I have a WIP fix for it that integrates the necessary files into the mirror. However I don't have permission to submit changes to the mirror yet. I filed http://crbug.com/1067615 . Once that's fixed you'll be able to pull in the allocator easily in vulkan/BUILD.gn.

Patch-set: 3
Reviewer: Gerrit User 1329751 <1329751@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>