Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-dbg-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8814312146949416689
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [49/467] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/BufferVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/BufferVk.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/vulkan/ContextVk.h(1273): error C2440: 'initializing': cannot convert from 'initializer list' to 'const rx::ContextVk::DirtyBits'
    C:\b\s\w\ir\cache\builder\angle\src\libANGLE/renderer/vulkan/ContextVk.h(1273): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-compile JOB_FAILED https://cr-buildbucket.appspot.com/build/8814312146949416705
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [50/467] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/DebugAnnotatorVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/DebugAnnotatorVk.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src\libANGLE/renderer/vulkan/ContextVk.h(1273): error C2440: 'initializing': cannot convert from 'initializer list' to 'const rx::ContextVk::DirtyBits'
    ../../src\libANGLE/renderer/vulkan/ContextVk.h(1273): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1300114 \u003c1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: CQ dry run failed."}