Revert "Support constant folding of common built-ins"
Part of a chain causing compile errors on Mac. Example:

../../third_party/angle/src/compiler/translator/IntermNode.cpp:1216:89: error: no member named 'sin' in namespace 'std'; did you mean 'sinf'?

http://build.chromium.org/p/chromium.gpu.fyi/builders/GPU%20Linux%20Builder/builds/33747

This reverts commit 2b1da6ed1dbe5960bed8c1b2fa3d33cb00c6c116.

Change-Id: I5d48932a6254d6d1e78966bb3891913d9450e08e