Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.angle.try/win-msvc-x86-dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8833333792290108865
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [357/433] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/SurfaceVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/SurfaceVk.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    C:\b\s\w\ir\cache\builder\angle\src\common/CircularBuffer.h(115): error C2440: 'return': cannot convert from 'std::_Array_iterator<_Ty,3>' to 'rx::impl::ImagePresentHistory *'
    with
    [
    _Ty=rx::impl::ImagePresentHistory
    ]
    C:\b\s\w\ir\cache\builder\angle\src\common/CircularBuffer.h(115): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.angle.try/win-msvc-x86-rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8833333792290108849
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [305/493] CXX obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/SurfaceVk.obj
    FAILED: obj/src/libANGLE/renderer/vulkan/angle_vulkan_backend/SurfaceVk.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\angle\third_party\depot_tools\win_too...(too long)
    ../../src\common/CircularBuffer.h(115): error C2440: 'return': cannot convert from 'std::_Array_iterator<_Ty,3>' to 'rx::impl::ImagePresentHistory *'
    with
    [
    _Ty=rx::impl::ImagePresentHistory
    ]
    ../../src\common/CircularBuffer.h(115): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cv
Attention: {"person_ident":"Gerrit User 1300114 \u003c1300114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ dry run failed."}